# Generated by Django 4.2 on 2023-04-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card_value',
            field=models.FloatField(max_length=100),
        ),
    ]
